### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by vishu97** [All3xJ/Hibernet#15]
Traceback (most recent call last):
  File "HibernetV2.2.py", line 1022, in <module>
    starturl() # questo fa startare la prima funzione del programma, che a sua volta ne starta un altra, poi un altra, fino ad arrivare all'attacco.
  File "HibernetV2.2.py", line 499, in starturl
    floodmode()
  File "HibernetV2.2.py", line 505, in floodmode
    proxymode()
  File "HibernetV2.2.py", line 549, in proxymode
    numthreads()
  File "HibernetV2.2.py", line 618, in numthreads
    multiplication()
  File "HibernetV2.2.py", line 627, in multiplication
    begin()
  File "HibernetV2.2.py", line 632, in begin
    loop()
  File "HibernetV2.2.py", line 718, in loop
    RequestDefaultHTTP(x+1).start() # starta la classe apposita
  File "/usr/lib/python3.4/threading.py", line 850, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
^CException ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.4/threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.4/threading.py", line 1076, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

**Comment by All3xJ** [comment]
you have probably chose too many threads

**Comment by SimplePlay** [comment]
i have the same problem. But on my virtual machine VMware i can select only 100 threads, but on my windows 10 pc i can select most than 30 000. What i do wrong?

**Comment by SimplePlay** [comment]
@All3xJ sono Italiano a proposito
